const urls = {
  admin: {
    lista_ventas_dia_vendedor: "admin/lista_ventas_dia",
    listausuarios: "admin/listausuarios",
    admin_sucursales: "admin/lista_sucursales",
    admin_medicos: "admin/lista_medicos",
    admin_tarjetas: "admin/lista_tarjetas",
    admin_bancos: "admin/lista_bancos",
    admin_mutuales: "admin/lista_mutuales",
    admin_clientes: "admin/clientes",
    dashboard_adm_prov: "admin/prov/",
    adm_prov_facturas: "admin/prov/facturas",
    adm_prov_cargar_factura: "admin/prov/cargar_factura",
    adm_prov_lista_prov: "admin/prov/lista_proveedores_adm",
    adm_prov_pagos: "admin/prov/pagos",
    adm_prov_remitos: "admin/prov/remitos",
    lista_conceptos_gastos: "admin/lista_conceptos_gastos",
    informe_cobros_tarjetas: "admin/ict",
    lista_cajas_admin: "admin/lista_cajas",
    panel_proveedores: "admin/panel_proveedores",
    panel_ventas: "admin/ventas",
    descuentos_adm: "admin/descuentos",
    stock_admin: "admin/stock_sucursal_admin/",
    eventos_admin: "admin/eventos/",
    dashboard_admin: "admin/",
  },
  ventas: {
    venta_directa: "ventas/Directa",
    venta_lclab: "ventas/LCLab",
    venta_lcstock: "ventas/LCStock",
    venta_multilab: "ventas/MultifLab",
    venta_monoflab: "ventas/MonofLab",
    venta_recetastock: "ventas/RecetaStockV2",
    lista_clientes_ventas: "ventas/listados/ListaClientesVentas",
    informe_ventas_dia_min: "ventas/informes/ventas_dias_min",
    ventas_vendedor: "ventas/informes/ventas_vendedor",
    totales_venta_vendedores: "ventas/informes/t_ventas_v",
  },
  caja: {
    lista_caja: "caja/lista_caja",
    caja_diaria: "caja/caja_diaria",
    cargar_gasto: "caja/CargaGasto/",
    lista_gastos: "caja/ListaGastos/",
    lista_cobros_sucursal: "caja/ListaCobros/",
    cierre_caja: "caja/",
    inicio_caja: "caja/",
    caja_admin: "caja/panelCajaAdmin/",
    listado_caja: "caja/",
    ventas_ingresadas: "caja/ventas_ingresadas",
    ventas_pendientes: "caja/ventas_pendientes",
    ventas_pendientes_lab: "caja/ventas_en_laboratorio",
    ventas_terminadas: "caja/ventas_terminadas",
    ventas_entregadas: "caja/ventas_entregadas",
    ventas_anuladas: "caja/ventas_anuladas",
    lista_clientes_caja: "caja/ListaClientesCaja",
    transferencias: "caja/lista_transferencia_sucursal",
    clientes_morosos: "caja/clientes_morosos",
  },
  laboratorio: {
    lista_operaciones_laboratorio: "laboratorio/lista_operaciones_laboratorio",
    lista_operaciones_total: "laboratorio",
    lista_operaciones_calibrado: "laboratorio/lista_operaciones_calibrado",
    lista_operaciones_pedidos: "laboratorio/lista_operaciones_pedidos",
    lista_operaciones_terminadas_taller:
      "laboratorio/lista_operaciones_terminadas_taller",
    lista_stock_taller: "laboratorio/stock_tallerv2",
    laboratorio_agregar_factura: "laboratorio/agregar_factura",
    laboratorio_lista_facturas: "laboratorio/facturas",
  },
  deposito: {
    nuevo_envio: "deposito/envio/nuevo_envio",
    lista_stock: "deposito/stock/listados/lista_stockv3",
    agregar_stock: "deposito/stock/agregar_stock_lote_v3",
    editar_multiplicadores: "deposito/stock/modificar_precios_categoria/",
    lista_subgrupos: "deposito/stock/listados/lista_subgrupos/",
    dashboard_deposito: "deposito/",
    dashboard_deposito_min: "deposito/index_min",
    arbol_codigos: "deposito/arbol_codigos",
    editar_precios: "deposito/stock/editar_precios",
    bajar_envios: "deposito/envio/descargar_envio",
    lista_control_stock: "deposito/control_stock/lista",
    nuevo_control_stock: "deposito/control_stock/carga",
    lista_codigos: "deposito/stock/listados/lista_codigos",
    imprimir_codigos: "deposito/imprimir_codigos",
  },
  distrib: {
    nueva_venta_distribuidora: "trabajos/nuevo",
    index_distribuidora: "trabajos/index",
    lista_operaciones_distribuidora: "trabajos/listado",
  },
};
